title: VariableSpacing docs
email: gustavo@hipertipo.com
description: VariableSpacing documentation
baseurl: ""
url: https://gferreira.github.io/VariableSpacing/

markdown: kramdown

version: 0.1.5

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

jekyll_tidy:
  exclude: []
  # ignore_env: development
  compress_html: false
